---

project_name: multik8s
before:
  hooks:
    - go mod tidy
builds:
  - binary: "multik8s"
    main: ./main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/eliasbokreta/multik8s/cmd.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
snapshot:
  name_template: "{{ .ShortCommit }}-SNAPSHOT"
