name: multik8s action
on:
  push:
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - '**/LICENSE'
      - '**/Makefile'
    tags:
      - v*
    branches:
      - master
  pull_request:
permissions:
  contents: read

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=3m

      - name: Run build
        run: make build

      - name: Run tests
        run: make test
